[package]
name = "calculator"
version = "0.1.0"
authors = ["Florian Blasius <flovanpt@posteo.de>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
orbtk = { git = "https://gitlab.redox-os.org/redox-os/orbtk.git" }